# Generated by Django 5.1 on 2024-08-12 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spotifytoken',
            old_name='users',
            new_name='user',
        ),
    ]
